# -*- encoding : utf-8 -*-
omniauth:
  facebook:
    key: 2345678980
    secret: asdasdasdasd
  vkontakte:
    key: 123456789
    secret: asdasdasdasdasd
    scope: notify,friends
  google_oauth2:
    key: asdasdjkashdkasjhd
    secret: asdlasdkajsdjlakjsd
    scope: userinfo.email,userinfo.profile,plus.me
    access_type: offline
    approval_prompt: ""


